import type { TravelType } from './types'

// 16 유형 정의 — 코드: [J|P][C|N][A|R][T|L]
export const TYPES: Record<string, TravelType> = {
  JCAT: {
    code: 'JCAT',
    name: '도시 정복자',
    en: 'The City Conqueror',
    tag: '철저한 계획 위에 함께 누비는 도시 모험가',
    summary:
      '지도 위에 분 단위로 동선을 그어두고, 친구들과 그 도시의 모든 골목을 정복합니다. 미슐랭 가이드와 로컬 맛집을 동시에 체크하는 사람.',
    cities: ['도쿄 — 시부야/신주쿠', '뉴욕 — 맨해튼', '이스탄불 — 베이오울루', '리스본 — 알파마'],
    bestWith: 'PNRL',
    worstWith: 'PNRT',
    companion: '체력 좋고 새로운 곳에 거리낌 없는 친구',
    checklist: ['분 단위 일정표 (구글맵 핀 포함)', '교통패스 ·SIM', '예약 확정 메일 출력본', '구급약·동선 변경시 백업 카페 3곳'],
  },
  JCAL: {
    code: 'JCAL',
    name: '도시 큐레이터',
    en: 'The Curator',
    tag: '혼자 조용히, 그러나 완벽하게 도시를 읽는 사람',
    summary:
      '전시 일정과 서점 위치, 카페 영업시간을 미리 정리해 둡니다. 인파를 피해 평일 오전에 가장 좋은 자리에 앉아 노트를 폅니다.',
    cities: ['파리 — 마레', '쿄토 — 기온', '베를린 — 미테', '타이베이 — 다안'],
    bestWith: 'PCRT',
    worstWith: 'JNAT',
    companion: '혼자가 가장 잘 어울리지만, 같은 취향의 한 명도 환영',
    checklist: ['주제별 큐레이션 리스트', '사색용 노트·만년필', '예매 티켓 PDF', '여유 30% 비워둔 일정표'],
  },
  JCRT: {
    code: 'JCRT',
    name: '미식 호스트',
    en: 'The Gourmet Host',
    tag: '도시의 가장 좋은 테이블을 예약해두는 사람',
    summary:
      '여행은 곧 식사 계획. 두 달 전에 예약을 잡고, 와인 페어링까지 미리 확인합니다. 동행자에게 맞춰 코스를 큐레이션하는 즐거움.',
    cities: ['산세바스티안', '방콕 — 통로', '리옹', '오사카 — 도톤보리'],
    bestWith: 'PCAT',
    worstWith: 'PNAL',
    companion: '맛에 대한 호기심이 큰 동행 1-3인',
    checklist: ['맛집 예약 확정', '드레스코드 의상', '위장약·소화제', '선물용 와인 한 병'],
  },
  JCRL: {
    code: 'JCRL',
    name: '호텔 라운저',
    en: 'The Hotel Lounger',
    tag: '도시 한복판, 가장 조용한 33층에 머무는 사람',
    summary:
      '리뷰를 백 개 넘게 읽고 호텔을 고릅니다. 도착하면 그 방이 곧 여행지. 룸서비스 메뉴와 어메니티를 알차게 즐깁니다.',
    cities: ['싱가포르 — 마리나베이', '도쿄 — 롯폰기', '두바이 — 다운타운', '홍콩 — 침사추이'],
    bestWith: 'PNRT',
    worstWith: 'PNAL',
    companion: '혼자 혹은 같은 휴식 취향의 파트너',
    checklist: ['조식 포함 객실', '독서용 책 2권', '수영복·욕가운', '조용한 플레이리스트'],
  },
  JNAT: {
    code: 'JNAT',
    name: '원정 대장',
    en: 'The Expedition Leader',
    tag: '팀을 이끌고 자연 속으로 들어가는 캡틴',
    summary:
      '장비 리스트, 고도, 날씨, 식수를 모두 체크합니다. 일행의 안전과 즐거움을 동시에 책임지는 든든한 대장.',
    cities: ['네팔 ABC 트레킹', '키나바루산', '지리산 종주', '파타고니아 W서킷'],
    bestWith: 'PNAT',
    worstWith: 'PCRL',
    companion: '비슷한 체력의 모험 동지 2-4인',
    checklist: ['방수 등산복·등산화', '헤드랜턴·여분 배터리', '비상식량 3일치', '응급 키트·호각'],
  },
  JNAL: {
    code: 'JNAL',
    name: '산악 철학자',
    en: 'The Mountain Philosopher',
    tag: '혼자 산을 오르며 생각을 정리하는 사람',
    summary: '텐트와 책 한 권. 정상보다 능선의 풍경이 더 중요합니다. 하루에 만 보를 걸으며 머릿속을 비웁니다.',
    cities: ['설악산 공룡능선', '스코틀랜드 하이랜드', '노르웨이 로포텐', '교토 키타야마'],
    bestWith: 'PCRT',
    worstWith: 'JCRT',
    companion: '혼자가 가장 좋다. 굳이 함께라면 말이 적은 한 명',
    checklist: ['가벼운 침낭·매트', '필름카메라', '얇은 책 한 권', '보온병·블랙커피'],
  },
  JNRT: {
    code: 'JNRT',
    name: '캠프 디렉터',
    en: 'The Camp Director',
    tag: '가족·친구를 위해 자연 휴양을 설계하는 사람',
    summary:
      '사이트 위치, 텐트 배치, 식단까지 세팅합니다. 별이 보이는 자리에 의자를 놓고, 모두에게 가장 좋은 풍경을 선물합니다.',
    cities: ['고성 — 송지호', '강릉 — 안반데기', '제주 — 비자림', '교토 외곽 캠핑장'],
    bestWith: 'PNAT',
    worstWith: 'PCAL',
    companion: '가족, 가까운 친구 그룹',
    checklist: ['사이트 사전 답사 사진', '공용 식단·식기', '랜턴·블루투스 스피커', '보드게임 한 박스'],
  },
  JNRL: {
    code: 'JNRL',
    name: '자연 명상가',
    en: 'The Nature Meditator',
    tag: '한적한 자연 속에서 천천히 회복하는 사람',
    summary:
      '온천, 산사, 호숫가의 작은 료칸. 사람 많은 곳을 피해 가장 조용한 시즌에 머뭅니다. 하루 두 끼와 긴 산책으로 충분.',
    cities: ['하코네 료칸', '양양 죽도', '오스트리아 할슈타트', '발리 우붓'],
    bestWith: 'PCRT',
    worstWith: 'PCAT',
    companion: '혼자, 또는 침묵을 즐기는 파트너',
    checklist: ['온천용 수건·실내복', '독서·일기', '오프라인 음악', '비행기 모드 24시간'],
  },
  PCAT: {
    code: 'PCAT',
    name: '야간 탐험대',
    en: 'The Night Crawlers',
    tag: '발길 닿는대로, 친구들과 도시의 밤을 누비는 사람',
    summary:
      '계획 없이 도착해 첫 골목에서 마주친 바에 들어갑니다. 친구의 친구를 만나고, 새벽까지 도시가 어떻게 잠드는지 지켜봅니다.',
    cities: ['베를린 — 크로이츠베르크', '타이베이 — 야시장', '방콕 — 카오산', '멕시코시티 — 콘데사'],
    bestWith: 'JCRT',
    worstWith: 'JNRL',
    companion: '체력 좋은 친구 2-4인, 영어 잘하면 보너스',
    checklist: ['여권 사본', '현금·카드 분리 보관', '충전기·보조배터리', '다음날 점심까지의 여유'],
  },
  PCAL: {
    code: 'PCAL',
    name: '골목 산책자',
    en: 'The Alley Wanderer',
    tag: '지도 없이 도시의 결을 따라가는 혼자의 사람',
    summary:
      '교통 카드 하나만 들고 거리로 나섭니다. 우연히 들어간 책방, 처음 보는 빵집, 이름 모르는 광장이 곧 여행의 주제가 됩니다.',
    cities: ['리스본 — 알파마', '교토 — 기온 뒷골목', '이스탄불 — 카라쿄이', '포르투'],
    bestWith: 'JCRT',
    worstWith: 'JNAT',
    companion: '혼자',
    checklist: ['필름카메라 또는 똑딱이', '편한 운동화', '메모지', '그 도시의 단편소설 한 권'],
  },
  PCRT: {
    code: 'PCRT',
    name: '카페 노마드',
    en: 'The Café Nomad',
    tag: '도시의 카페를 옮겨다니며 함께 시간을 보내는 사람',
    summary:
      '오늘은 이 카페, 내일은 저 베이커리. 일정 없이 좋아하는 사람과 천천히 머무는 시간이 곧 여행. 즉흥적인 미식 산책.',
    cities: ['멜버른', '쿄토', '리스본', '코펜하겐'],
    bestWith: 'JCAL',
    worstWith: 'JNAL',
    companion: '취향이 비슷한 한 명',
    checklist: ['가벼운 가방', '독서·노트', '에어팟', '현지 카페 SNS 저장 리스트 (참고용)'],
  },
  PCRL: {
    code: 'PCRL',
    name: '도시 휴양객',
    en: 'The Urban Recharger',
    tag: '계획 없이, 혼자, 도시에서 조용히 회복하는 사람',
    summary:
      '도시에 머물지만 모든 약속을 끄고 들어옵니다. 호텔 라운지, 미술관, 그리고 익명의 카페. 도시의 소음이 오히려 위로가 됩니다.',
    cities: ['도쿄 — 야네센', '파리 — 좌안', '뉴욕 — 그리니치빌리지', '서울 — 성북동'],
    bestWith: 'PCAT',
    worstWith: 'JNAT',
    companion: '혼자',
    checklist: ['호텔 한 곳 길게 예약', '전시 표 두 장', '비행기 모드', '에세이 한 권'],
  },
  PNAT: {
    code: 'PNAT',
    name: '즉흥 모험단',
    en: 'The Wild Crew',
    tag: '친구들과 차에 짐 싣고 떠나는 자연 모험가',
    summary:
      '어느 산이든, 어느 계곡이든. 여정 자체가 즐겁습니다. 길에서 만나는 모든 우연을 받아들이는 자유로운 팀.',
    cities: ['강원도 동해안', '아이슬란드 링로드', '뉴질랜드 남섬', '조지아 코카서스'],
    bestWith: 'JNAT',
    worstWith: 'JCRL',
    companion: '운전·요리 분담 가능한 친구 2-3인',
    checklist: ['차량 점검·연료', '캠핑 의자·테이블', '음악 플레이리스트', '오프라인 지도'],
  },
  PNAL: {
    code: 'PNAL',
    name: '떠돌이 모험가',
    en: 'The Lone Drifter',
    tag: '지도 없이 혼자 자연 속으로 사라지는 사람',
    summary:
      '배낭 하나, 텐트 하나. 정해진 일정은 없습니다. 길을 잃는 것도 여행의 일부. 가장 멀리, 가장 조용한 곳까지.',
    cities: ['몽골 초원', '파타고니아', '아이슬란드 하이랜드', '사하라'],
    bestWith: 'JCRT',
    worstWith: 'JCRT',
    companion: '혼자',
    checklist: ['GPS·종이지도', '위성통신기기', '비상식량 5일치', '여분 양말 4켤레'],
  },
  PNRT: {
    code: 'PNRT',
    name: '즉흥 캠퍼',
    en: 'The Easy Camper',
    tag: '친구들과 자연에서 느긋하게 머무는 사람',
    summary:
      '장비는 단출하게, 음식은 푸짐하게. 모닥불 앞에서 별을 보며 이야기를 나누는 밤이 곧 여행의 전부.',
    cities: ['가평 자라섬', '고성 송지호', '프로방스 라벤더밭', '발리 우붓 외곽'],
    bestWith: 'JNRT',
    worstWith: 'JCAT',
    companion: '친한 친구 그룹, 혹은 가족',
    checklist: ['타프·캠핑 의자', '공용 쿨러·맥주', '기타 또는 스피커', '마시멜로·장작'],
  },
  PNRL: {
    code: 'PNRL',
    name: '자유의 새',
    en: 'The Free Bird',
    tag: '발길 닿는대로, 혼자 자연을 거니는 사람',
    summary:
      '오늘은 호숫가에서, 내일은 산자락에서. 사람 없는 곳을 골라 다닙니다. 일정 대신 마음의 속도에 맞춥니다.',
    cities: ['제주 서쪽', '라오스 루앙프라방', '발리 우붓', '치앙마이 외곽'],
    bestWith: 'JCAT',
    worstWith: 'JCAT',
    companion: '혼자',
    checklist: ['배낭 하나로 충분한 짐', '해먹·얇은 담요', '필름카메라', '노트·만년필'],
  },
}
